[project]
name = "emailagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.57.0",
    "google-generativeai>=0.8.6",
    "langgraph>=1.0.5",
    "notebook>=7.5.1",
    "python-dotenv>=1.2.1",
]
